[package]
name = "task-01"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10.0"

[dev-dependencies]
criterion = "0.8.2"

[[bench]]
name = "linear_search"
# Use criterion instead of builtin bench (which is unstable yet)
harness = false
